CREATE DATABASE Customer ;
USE Customer;
SELECT * FROM customer_shopping_behavior_cleaned;

#1.What is the total revenue generated by male versus female customers.
SELECT gender, SUM(purchase_amount) AS total_revenue
FROM customer_shopping_behavior_cleaned 
GROUP BY gender;

#2.Which customers use their discount but history spend more than the average purchase amount.
SELECT customer_id, purchase_amount FROM customer_shopping_behavior_cleaned
WHERE discount_applied = 'Yes' AND purchase_amount > (
      SELECT AVG(purchase_amount)
      FROM customer_shopping_behavior_cleaned 
  );
  #3. Which are the top five products with the highest average rating?
  SELECT
    item_purchased,
    ROUND(AVG(review_rating),2) AS average_rating
FROM customer_shopping_behavior_cleaned 
GROUP BY item_purchased
ORDER BY average_rating DESC
LIMIT 5;
  
#4.Compare the average purchase amount between Standard and Express shipping.
SELECT
    shipping_type,
    ROUND(AVG(purchase_amount),2) AS average_purchase_amount
FROM customer_shopping_behavior_cleaned
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

#5.Do subscriber customers spend more? Compare average spend and total revenue 
#between subscribers and non-subscribers.
SELECT
    subscription_status,
    ROUND(AVG(purchase_amount),2) AS average_spend,
    SUM(purchase_amount) AS total_revenue
FROM customer_shopping_behavior_cleaned
GROUP BY subscription_status;

#6.Which five products have the highest percentage of purchases with discounts applied?
SELECT item_purchased, 
ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) 
AS discount_percentage FROM customer_shopping_behavior_cleaned
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

#7. Segment customers into new, returning and loyal based on their total number
# of previous purchases and show the count of each segment.
SELECT customer_segment, COUNT(*) AS customer_count FROM (SELECT customer_id,CASE
 WHEN previous_purchases <= 5 THEN 'New' WHEN previous_purchases <= 10 THEN 'Returning'
	ELSE 'Loyal' END AS customer_segment FROM customer_shopping_behavior_cleaned
) AS segmented_customers
GROUP BY customer_segment
ORDER BY customer_count DESC;

#8.Are customers with more than 5 previous purchases more likely to subscribe.
SELECT subscription_status, COUNT(*) AS customer_count
FROM customer_shopping_behavior_cleaned
WHERE previous_purchases > 5
GROUP BY subscription_status;

#9.What is the revenue contribution of each age group
SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customer_shopping_behavior_cleaned
GROUP BY age_group
ORDER BY total_revenue DESC;

